### ISSUE TITLE
TypeError: unsupported format string passed to list.__format__

### ISSUE THREAD

**Issue by Cavendish088** [dreamcontinue/CNN#1]
> hhr@ubuntu:~/CNN-master$ python3 train.py --config configs/resnet_cifar100.yml
/home/hhr/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/hhr/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/hhr/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/hhr/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/hhr/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/hhr/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
train.py:185: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(fp)
RUNDIR: runs/resnet_cifar100/52820
Files already downloaded and verified
CifarResNet : Depth : 56 , Layers for each block : 9
/home/hhr/CNN-master/models/CifarResNet.py:69: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(m.weight)
INFO:CNN:Using cross_entropy with {} params
INFO:CNN:No checkpoint found at 'runs/resnet_cifar100/52820/save_model.pkl'
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    train(cfg, writer, logger)
  File "train.py", line 91, in train
    time_string(), epoch, epochs, need_time, scheduler.get_last_lr()) +  # v<1.4 optimizer.param_groups[0]['lr']
TypeError: unsupported format string passed to list.__format__

**Comment by Cavendish088** [comment]
Change scheduler.get_last_lr() to scheduler.get_last_lr()[0] can solve my problem.
